[tox]
min_version = 4.30

env_list =
    python{3.11}-dj52-wagtail70
    python{3.12}-dj52-wagtail73
    python{3.13}-dj52-wagtail74
    python{3.14}-dj{52,60}-wagtail{74}

[gh-actions]
python =
    3.10: py3.10
    3.11: py3.11
    3.12: py3.12
    3.13: py3.13
    3.14: py3.14

[testenv]
package = wheel
wheel_build_env = .pkg
use_frozen_constraints = true
constrain_package_deps = true

pass_env =
    FORCE_COLOR
    NO_COLOR

set_env =
    PYTHONPATH = {toxinidir}
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONDEVMODE = 1

    python3.12: COVERAGE_CORE=sysmon
    python3.13: COVERAGE_CORE=sysmon
    python3.14: COVERAGE_CORE=sysmon

extras = testing

deps =
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    wagtail70: wagtail>=7.0,<7.1
    wagtail73: wagtail>=7.3,<7.4
    wagtail74: wagtail>=7.4,<7.5

commands_pre =
    python -I {toxinidir}/tests/manage.py migrate
commands =
    python -Im coverage run {toxinidir}/tests/manage.py test --deprecation all {posargs: -v 2}

[testenv:coverage-report]
base_python = python3.14
package = skip
deps =
    coverage>=7.0,<8.0
commands =
    python -Im coverage combine
    python -Im coverage report -m

[testenv:wagtailmain]
description = Test with latest Wagtail main branch
base_python = python3.14
deps =
    wagtailmain: git+https://github.com/wagtail/wagtail.git@main#egg=Wagtail

[testenv:interactive]
package = editable
description = An interactive environment for local testing purposes
base_python = python3.14

deps =
    wagtail>=7.0,<7.1

commands_pre =
    python {toxinidir}/tests/manage.py makemigrations
    python {toxinidir}/tests/manage.py migrate
    python {toxinidir}/tests/manage.py shell -c "from django.contrib.auth.models import User;(not User.objects.filter(username='admin').exists()) and User.objects.create_superuser('admin', 'super@example.com', 'changeme')"
    python {toxinidir}/tests/manage.py createcachetable

commands =
    {posargs:python {toxinidir}/tests/manage.py runserver 0.0.0.0:8020}

set_env =
    INTERACTIVE = 1
