[tox]
min_version = 4.30

env_list =
    python{3.11}-django5.2-wagtail7.0
    python{3.12}-django5.2-wagtail7.3
    python{3.13}-django5.2-wagtail7.4
    python{3.14}-django{5.2,6.0}-wagtail{7.4}

[gh-actions]
python =
    3.10: python3.10
    3.11: python3.11
    3.12: python3.12
    3.13: python3.13
    3.14: python3.14

[testenv]
package = wheel
wheel_build_env = .pkg
use_frozen_constraints = true
constrain_package_deps = true

pass_env =
    FORCE_COLOR
    NO_COLOR

set_env =
    PYTHONPATH = {toxinidir}
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONDEVMODE = 1

    python3.12: COVERAGE_CORE=sysmon
    python3.13: COVERAGE_CORE=sysmon
    python3.14: COVERAGE_CORE=sysmon

extras = testing

deps =
    django5.2: Django>=5.2,<5.3
    django6.0: Django>=6.0,<6.1
    wagtail7.0: wagtail>=7.0,<7.1
    wagtail7.3: wagtail>=7.3,<7.4
    wagtail7.4: wagtail>=7.4,<7.5

commands_pre =
    python -I {toxinidir}/tests/manage.py migrate
commands =
    python -Im coverage run {toxinidir}/tests/manage.py test --deprecation all {posargs: -v 2}

[testenv:coverage-report]
base_python = python3.14
package = skip
deps =
    coverage>=7.0,<8.0
commands =
    python -Im coverage combine
    python -Im coverage report -m

[testenv:wagtailmain]
description = Test with latest Wagtail main branch
base_python = python3.14
deps =
    wagtailmain: git+https://github.com/wagtail/wagtail.git@main#egg=Wagtail

[testenv:interactive]
package = editable
description = An interactive environment for local testing purposes
base_python = python3.14

deps =
    wagtail>=7.0,<7.1

commands_pre =
    python {toxinidir}/tests/manage.py makemigrations
    python {toxinidir}/tests/manage.py migrate
    python {toxinidir}/tests/manage.py shell -c "from django.contrib.auth.models import User;(not User.objects.filter(username='admin').exists()) and User.objects.create_superuser('admin', 'super@example.com', 'changeme')"
    python {toxinidir}/tests/manage.py createcachetable

commands =
    {posargs:python {toxinidir}/tests/manage.py runserver 0.0.0.0:8020}

set_env =
    INTERACTIVE = 1
