Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    
    config.vm.provider "virtualbox" do |v|
      v.name = "wagtailmedia"
    end
    
    config.vm.network "forwarded_port", guest: 8020, host: 8020
    config.vm.provision :shell, path: "provision.sh"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../", "/vagrant"
end
