# Generated by Django 2.0.2 on 2018-03-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateField(null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date_to',
            field=models.DateField(blank=True, help_text='Not required if event is on a single day', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='eventpagerelatedmedia',
            name='title',
            field=models.CharField(help_text='Link title', max_length=255),
        ),
    ]
