# Generated by Django 3.2.5 on 2021-07-31 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmedia.tests.testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailmedia_tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogStreamPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("date", models.DateField(verbose_name="Post date")),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.CharBlock(
                                    form_classname="full title", icon="title"
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.core.blocks.RichTextBlock(icon="pilcrow"),
                            ),
                            (
                                "media",
                                wagtailmedia.tests.testapp.models.TestMediaBlock(
                                    icon="media"
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="custommedia",
            name="duration",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Duration in seconds",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="duration",
            ),
        ),
    ]
