# Generated by Django 4.1.4 on 2022-12-27 10:19

from django.db import migrations
import tests.testapp.models
import wagtail.blocks
import wagtail.fields
import wagtailmedia.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailmedia_tests", "0002_blogstreampage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogstreampage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(form_classname="title", icon="title"),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock(icon="pilcrow")),
                    ("media", tests.testapp.models.TestMediaBlock(icon="media")),
                    ("video", wagtailmedia.blocks.VideoChooserBlock(icon="media")),
                    ("audio", wagtailmedia.blocks.AudioChooserBlock(icon="media")),
                ],
                use_json_field=True,
            ),
        ),
    ]
