# Generated by Django 3.0.5 on 2020-08-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True, verbose_name='duration'),
        ),
    ]
