# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mediainfo',
            field=models.TextField(blank=True, null=True, verbose_name='mediainfo'),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True, verbose_name='duration'),
        ),
    ]
