# Generated by Django 2.2.8 on 2020-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds', verbose_name='duration'),
        ),
    ]
