name: Publish to PyPI

on:
  release:
    types: [published]

permissions: {}

jobs:
  # https://docs.pypi.org/trusted-publishers/using-a-publisher/
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'torchbox' && github.event.action == 'published'
    environment:
      name: 'release'
      url: https://pypi.org/p/wagtailmedia
    permissions:
      contents: read # to fetch code (actions/checkout)
      id-token: write  # Mandatory for trusted publishing
    steps:
      - name: 🔒 Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            ghcr.io:443
            pkg-containers.githubusercontent.com:443
            pypi.org:443
            upload.pypi.org:443
            files.pythonhosted.org:443
            fulcio.sigstore.dev:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.14'

      - name: ⬇️ Install build dependencies
        run: |
          python -Im pip install -U flit

      - name: 🏗️ Build
        run: python -Im flit build

      - name: 🚀 Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # v1.14.0
