name: Publish to PyPI

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  # https://docs.pypi.org/trusted-publishers/using-a-publisher/
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: github.repository_owner == 'torchbox' && github.event.action == 'published'
    environment:
      name: 'release'
      url: https://pypi.org/p/wagtailmedia
    permissions:
      contents: read # to fetch code (actions/checkout)
      id-token: write  # Mandatory for trusted publishing
    steps:
      - name: 🔒 Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            ghcr.io:443
            pkg-containers.githubusercontent.com:443
            pypi.org:443
            upload.pypi.org:443
            files.pythonhosted.org:443
            fulcio.sigstore.dev:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'

      - name: ⬇️ Install build dependencies
        run: |
          python -Im pip install -U flit

      - name: 🏗️ Build
        run: python -Im flit build

      - name: 🚀 Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
