name: Ruff

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411  # v2.19.4

      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          files.pythonhosted.org:443
          objects.githubusercontent.com:443
          github.com:443
          pypi.org:443
          api.github.com:443

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        persist-credentials: false

    - run: python -Im pip install --user ruff==0.15.13

    - name: Run ruff
      working-directory: ./src
      run: ruff check --output-format=github wagtailmedia
