name: Ruff

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1

      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          files.pythonhosted.org:443
          objects.githubusercontent.com:443
          github.com:443
          pypi.org:443
          api.github.com:443

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - run: python -Im pip install --user ruff==0.16.1

    - name: Run ruff
      working-directory: ./src
      run: ruff check --output-format=github wagtailmedia
